### ISSUE TITLE
已删除。

### ISSUE THREAD

**Issue by LiBinFS** [zhanghao-web/zhanghao-web.github.io#1]
原文发于掘金和 segmentfault：https://juejin.im/post/5a1e11b86fb9a0451d413977

**Comment by zhanghao-web** [comment]
不好意思，没经过你同意，搬到我的博客里来，我这个博客只是为了个人记录好的文章的，来自己学习的。另文章末尾或头部我都标明原文地址。如真的不可以用，我立马删除。

**Comment by zhanghao-web** [comment]
不好意思，没经过你同意，搬到我的博客里来，我这个博客只是为了个人记录好的文章的，来自己学习的。另文章末尾或头部我都标明原文地址。如真的不可以用，我立马删除。
